---
# https://github.com/pages-themes/cayman

theme: jekyll-theme-cayman
layout: page

title: "QuatroPe"
description: "We create quality scientific software"

sitecolor: "#205692"
logo: assets/imgs/quatrope_logo.png
favicon: assets/imgs/favicon.ico


navbar:
    - title: Projects
      link: projects

    - title: People
      link: projects

    - title: Publications
      link: pubs

    - title: Legal
      link: legal
