---
# https://github.com/pages-themes/cayman

theme: jekyll-theme-cayman
layout: page

title: "QuatroPe"
description: "We create quality scientific software"

sitecolor: "#205692"
logo: assets/imgs/quatrope_logo.png
favicon: assets/imgs/favicon.ico

license_link: legal
coc_link: code_of_conduct
contact_link: contact

navbar:
    - title: Projects
      link: projects

    - title: Publications
      link: pubs

    - title: People
      link: people

people:
    - name: Bruno Sanchez
      link: "https://scholars.duke.edu/person/bruno.sanchez"
      description:
          Bruno is an astrophysicist with extensive knowledge in programming
          and mentoring students.

          His main research topics include Cosmology, and Data Analysis in Time
          Domain Astronomy.

          He is currently employed by the Physics Department of Duke University
          in a postdoctoral position.

          He is member of the Dark Energy Science Collaboration that will probe into cosmology using data from the
          Legacy Survey of Space and Time.

    - name: Martin Beroiz
      link: "https://martinberoiz.org/"
      description:
          Martin is an expert Python and C programmer with extensive skills in web development and the design of libraries and applications.

          He is currently employed by the Univesity of Texas Rio Grande Valley in a postdoctoral position.

          His interests include API Design, User Experience, Astronomy Software and Automation.

    - name: Juan B Cabral
      link: "https://jbcabral.org"
      description:
          Juan is a full stack developer and software engineer with extensive Python, web and scientific programming experience.

          He is the co-founder of Scipy LatAm Community, has served as the Chair of PyCon Argentina 2012
          --the Python Argentina flagship conference-- and has been the Chair of SciPy LatAm 2015.

          He currently holds a post-doctoral researcher position at CIFASIS-CONICET, a national research institution in Argentina.

          His interests include Machine Learning, Astrophysics data analysis, Scientific Software Engineering, and Experimental Economy.


quatrope_toplevel_projects:
    - name: Astroalign
      description: "Astroalign is a python module that will try to align two stellar astronomical images, especially when there is no WCS information available."
      link: "https://astroalign.readthedocs.io/"
    - name: Properimage
      description: "Properimage is an implementation of the algorithms described in Zackay & Ofek 2017 papers, “How to coadd images”"
      link: "https://properimage.readthedocs.io/"
    - name: Carpyncho
      description: "Carpyncho, is a catalog browser that we hope will be reutilized to search for and characterize time variable data of the ~PiB size VVV/VVVx survey."
      link: "https://carpyncho.github.io/"
    - name: PyCF3
      description: "Cosmicflows Galaxy Distance-Velocity Calculator client for Python."
      link: "https://pycf3.readthedocs.io/"


publications:

    - citation: "Beroiz, M., Cabral, J. B., & Sanchez, B. (2020). Astroalign: A Python module for astronomical image registration. Astronomy and Computing, 100384."
      link: "https://www.sciencedirect.com/science/article/pii/S221313372030038X"

    - citation: "Sánchez, B., Lares, M., Beroiz, M., Cabral, J. B., Gurovich, S., Quiñones, C., ... & Tornatore, M. (2019). Machine learning on difference image analysis: A comparison of methods for transient detection. Astronomy and Computing, 28, 100284."
      link: "https://www.sciencedirect.com/science/article/pii/S2213133718300982"

    - citation: "Cabral, J. B., Sánchez, B., Ramos, F., Gurovich, S., Granitto, P. M., & Vanderplas, J. (2018). From FATS to feets: Further improvements to an astronomical feature extraction tool based on machine learning. Astronomy and computing, 25, 213-220."
      link: "https://www.sciencedirect.com/science/article/abs/pii/S2213133718300581"

    - citation: "Cabral, J. B., Sánchez, B., Beroiz, M., Domínguez, M., Lares, M., Gurovich, S., & Granitto, P. (2017). Corral framework: Trustworthy and fully functional data intensive parallel astronomical pipelines. Astronomy and computing, 20, 140-154."
      link: "https://www.sciencedirect.com/science/article/abs/pii/S2213133717300069"

