---
# https://github.com/pages-themes/cayman

theme: jekyll-theme-cayman
layout: page

title: "QuatroPe"
description: "We create quality scientific software"

sitecolor: "#205692"
logo: assets/imgs/quatrope_logo.png
favicon: assets/imgs/favicon.ico


navbar:
    - title: Projects
      link: projects

    - title: People
      link: projects

    - title: Publications
      link: pubs

    - title: Legal
      link: legal

quatrope_toplevel_projects:
    - name: Carpyncho
      description: "Carpyncho, is a catalog browser that we hope will be reutilized to search for and characterize time variable data of the ~PiB size VVV/VVVx survey."
      link: "https://carpyncho.github.io/"
